### ISSUE TITLE
mounting os0: as RW is a VERY VERY VERY BAD IDEA!

### ISSUE THREAD

**Issue by zecoxao** [tomtomdu80/VitaRW#3]
mounting os0 as RW will lead to bricks, so please, leave this one alone. doing bad things to vs0: can lead to a semi-brick but you can always recover with recovery menu (this on a PSTV, unknown if this works on PSVITA and PSVITA2000).
Issuer's note: This is why in the ps3 scene nobody ever mounted anything else other than dev_flash (vs0 to the ps3) and usb/hdd devices. You CAN mount the flash but it's a VERY BAD IDEA!

Thank you for your time :)

**Comment by ghost** [comment]
yes, as your existence.

**Comment by astronautlevel2** [comment]
I mean, he's right though. Aside from specialized tools like downgrades, touching os0: is horrible. It's not something that should be manually managed.

**Comment by sirocyl** [comment]
Yeah, I'm with @zecoxao and @astronautlevel2 on this one. os0: modification should be left to specific tools. It's not wise to modify files there, considering they control boot and recovery things, and are encrypted in ways where we can't even modify them if we wanted to.

The people who do need to modify os0:. should be able to write the modification to allow this, and build this tool themselves.

**Comment by AlienDog** [comment]
Sorry for my new in C. First, I met an error in make:cannot found -lSceVshBridge_stub.Then I compiled the extra folder with 'make' and got 'libSceVshBridge_stub.a' .After that ,I copy the 'libSceVshBridge_stub.a' to arm-vita-eabi\lib. I thought the problem was solved,but I got the error:undefined reference to 'vshIoUmount'. How to solve the problem? Many thanks!

**Comment by MisterAlex95** [comment]
@AlienDog  create a new Issue. You new to update your toolchain.

**Comment by MajorTomSec** [comment]
i've just not bothered figuring out what partitions had which ID. This was just to show how all partitions could be written. I've not even provided any build, so it's up to the people who provided builds to remove access to os0.

**Comment by Yoti** [comment]
Just note: 0x300 is vs0.
